# Generated by Django 3.1.1 on 2022-04-07 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='ll',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_approved_lll', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ll',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_lll', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ll',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_lll', to=settings.AUTH_USER_MODEL),
        ),
    ]
