# Generated by Django 3.1.1 on 2022-04-08 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220407_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ll',
            name='order',
        ),
    ]
