# Generated by Django 3.1.1 on 2022-04-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ll_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ll',
            field=models.ManyToManyField(to='core.Ll'),
        ),
    ]
