# Generated by Django 3.1.1 on 2022-04-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_ll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ll',
            options={'verbose_name_plural': 'Lls'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='ll',
        ),
        migrations.AddField(
            model_name='ll',
            name='order',
            field=models.ManyToManyField(blank=True, to='core.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='Lls',
            field=models.ManyToManyField(related_name='_order_Lls_+', to='core.Ll'),
        ),
    ]
