# Generated by Django 3.1.1 on 2022-04-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220409_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ll',
            name='order',
            field=models.ManyToManyField(to='core.Order'),
        ),
    ]
