# Generated by Django 3.1.1 on 2022-04-11 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20220411_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_approved_Order', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_Order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'order',
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Lls',
        ),
        migrations.DeleteModel(
            name='Ll',
        ),
        migrations.AddField(
            model_name='order',
            name='orderitem',
            field=models.ManyToManyField(related_name='_order_orderitem_+', to='core.Orderitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_Order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ManyToManyField(related_name='_orderitem_order_+', to='core.Order'),
        ),
    ]
