# Generated by Django 3.1.1 on 2022-04-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220411_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'orderitem'},
        ),
    ]
