# Generated by Django 3.1.1 on 2022-04-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220411_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderitem',
            field=models.ManyToManyField(related_name='orderitem_order', to='core.Orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ManyToManyField(related_name='orderitem_order', to='core.Order'),
        ),
    ]
