# Generated by Django 3.1.1 on 2022-04-12 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20220412_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_Price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderitem',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendorItems',
        ),
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(related_name='order_item_order', to='core.OrderItem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendoritem', to='core.vendoritems'),
        ),
        migrations.AlterField(
            model_name='order',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_approved_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_orderitem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_orderitem', to=settings.AUTH_USER_MODEL),
        ),
    ]
