# Generated by Django 4.0.3 on 2022-03-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('phone', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
